spring:
  application:
    name: rsocket-trading-service
  mongodb:
    database: trading-service
    port: 27018

service:
  stock:
    host: localhost
    port: 7070
  user:
    host: localhost
    port: 7071
